# Generated by Django 5.2.16 on 2026-08-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginevent',
            name='logout_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de déconnexion'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de connexion'),
        ),
    ]
