# Generated by Django 5.2.16 on 2026-08-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('cameroon', 'Cameroun'), ('chad', 'Tchad'), ('drc', 'RDC'), ('senegal', 'Sénégal'), ('burkina_faso', 'Burkina Faso'), ('niger', 'Niger')], max_length=20, verbose_name='pays'),
        ),
    ]
