# Generated by Django 5.2.16 on 2026-08-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('cameroon', 'Cameroun'), ('chad', 'Tchad'), ('drc', 'RDC'), ('senegal', 'Sénégal'), ('burkina_faso', 'Burkina Faso'), ('niger', 'Niger'), ('all', 'Tous les pays')], max_length=20, verbose_name='pays'),
        ),
    ]
