# Generated by Django 5.2.16 on 2026-08-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcosystemTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('en-developpement', 'En développement')], default='en-developpement', max_length=20, verbose_name='statut')),
                ('url', models.URLField(blank=True, verbose_name='lien')),
            ],
            options={
                'verbose_name': 'outil',
                'verbose_name_plural': "outils de l'écosystème",
                'ordering': ['name'],
            },
        ),
    ]
