# Generated by Django 5.2.16 on 2026-08-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='chemin visité')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
            ],
            options={
                'verbose_name': 'visite',
                'verbose_name_plural': 'visites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='analytics_v_created_50bde4_idx')],
            },
        ),
    ]
